# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [387]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

In [388]:
import numpy as np

In [389]:
dataFrame = pd.DataFrame(df)

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

**Dataset Shape**

In [390]:
shape = np.shape(dataFrame)
print(shape)

(891, 12)

**Min Value**

In [391]:
min = dataFrame.min()
print(min)

PassengerId                      1
Survived                         0
Pclass                           1
Name           Abbing, Mr. Anthony
Sex                         female
Age                           0.42
SibSp                            0
Parch                            0
Ticket                      110152
Fare                           0.0
Cabin                          A10
Embarked                         C
dtype: object

**Max Value**

In [392]:
max = dataFrame.max()
print(max)

PassengerId                            891
Survived                                 1
Pclass                                   3
Name           van Melkebeke, Mr. Philemon
Sex                                   male
Age                                   80.0
SibSp                                    8
Parch                                    6
Ticket                           WE/P 5735
Fare                              512.3292
Cabin                                    T
Embarked                                 S
dtype: object

**Mean Passenger Age**

In [393]:
mean = dataFrame["Age"].mean()
print(mean)

29.69911764705882

**1st Ten Rows of Dataset**

In [394]:
dataFrame.iloc[:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

**Select Name Column**

In [395]:
name_column = dataFrame["Name"].to_frame()
name_column

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

**Select Certain Columns**

In [396]:
select_columns = dataFrame[["Name", "Age", "Ticket", "Embarked"]]
select_columns

,Name,Age,Ticket,Embarked
0,"Braund, Mr. Owen Harris",22.0,A/5 21171,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,PC 17599,C
2,"Heikkinen, Miss Laina",26.0,STON/O2. 3101282,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,113803,S
4,"Allen, Mr. William Henry",35.0,373450,S
...,...,...,...,...
886,"Montvila, Rev. Juozas",27.0,211536,S
887,"Graham, Miss Margaret Edith",19.0,112053,S
888,"Johnston, Miss Catherine Helen ""Carrie""",NaN,W./C. 6607,S
889,"Behr, Mr. Karl Howell",26.0,111369,C
890,"Dooley, Mr. Patrick",32.0,370376,Q

**Select Single Row**

In [397]:
row = dataFrame.iloc[9].to_frame()
row

                                               9
PassengerId                                   10
Survived                                       1
Pclass                                         2
Name         Nasser, Mrs. Nicholas (Adele Achem)
Sex                                       female
Age                                         14.0
SibSp                                          1
Parch                                          0
Ticket                                    237736
Fare                                     30.0708
Cabin                                        NaN
Embarked                                       C

**Rectangular Selection**

In [398]:
rect_selection = dataFrame.loc[45:59, "Survived":"Name"]
rect_selection

    Survived  Pclass                                               Name
45         0       3                           Rogers, Mr. William John
46         0       3                                  Lennon, Mr. Denis
47         1       3                           O'Driscoll, Miss Bridget
48         0       3                                Samaan, Mr. Youssef
49         0       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)
50         0       3                          Panula, Master Juha Niilo
51         0       3                       Nosworthy, Mr. Richard Cater
52         1       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)
53         1       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...
54         0       1                     Ostby, Mr. Engelhart Cornelius
55         1       1                                  Woolner, Mr. Hugh
56         1       2                                   Rugg, Miss Emily
57         0       3                                Novel, Mr. Mansouer
58         1       2                        West, Miss Constance Mirium
59         0       3                  Goodwin, Master William Frederick

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

**Older Than 60**

In [399]:
older_than_60 = dataFrame[dataFrame["Age"] > 60]
older_than_60

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

**Fare Above 100 & 1st Class Passenger**

In [400]:
wealthy_passengers = dataFrame[(dataFrame["Fare"] > 100) & (dataFrame["Pclass"] == 1)]
wealthy_passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

**Passengers with Missing Age Values**

In [401]:
missing_age = dataFrame[dataFrame["Age"].isna()]
missing_age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

**Reverse Row Order**

In [402]:
reverse_order = dataFrame.reindex(index=dataFrame.index[::-1])
reverse_order

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

**Remove One Column**

In [403]:
missing_a_column = dataFrame.drop("Name", axis=1)
missing_a_column

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

**Remove Rows with NaN Age Values**

In [404]:
no_nan_age_rows = dataFrame.drop(dataFrame.index[dataFrame["Age"].isna()])
no_nan_age_rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

**New Column of Fares in Euros**

In [405]:
conversion_rate = 0.86
fare_euros_df = dataFrame.copy()
fare_euros_df["Fare Euros"] = fare_euros_df["Fare"] * conversion_rate
fare_euros_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000

**Subtract Mean Age from Each Age value**

In [406]:
mean_age = dataFrame["Age"].mean()
subtract_mean_age_df = dataFrame.copy()
subtract_mean_age_df["Age"] = subtract_mean_age_df["Age"] - mean_age
subtract_mean_age_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,7.7500,NaN,Q

**Subtraction of Custom Array From 2 Columns**

In [407]:
random_numbers = np.random.randint(low=0, high=10, size=len(dataFrame))
selected_num_columns = ["Pclass", "Fare"]
subtracted_df = dataFrame.copy()
subtracted_df[selected_num_columns] = subtracted_df[selected_num_columns].sub(random_numbers, axis=0)
subtracted_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,-2,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,2.2500,NaN,S
1,2,1,-4,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,66.2833,C85,C
2,3,1,-1,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,3.9250,NaN,S
3,4,1,-7,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,45.1000,C123,S
4,5,0,-3,"Allen, Mr. William Henry",male,35.0,0,0,373450,2.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,11.0000,NaN,S
887,888,1,-4,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,25.0000,B42,S
888,889,0,-1,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,19.4500,NaN,S
889,890,1,-4,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,25.0000,C148,C
890,891,0,-4,"Dooley, Mr. Patrick",male,32.0,0,0,370376,0.7500,NaN,Q

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

**Number of Characters in Each Name**

In [440]:
number_char_name = pd.DataFrame(data=dataFrame["Name"].str.len())
number_char_name

     Name
0      23
1      51
2      21
3      44
4      24
..    ...
886    21
887    27
888    39
889    21
890    19

[891 rows x 1 columns]

**Fare and Age Difference**

In [441]:
fare_age_diff = pd.DataFrame(data = dataFrame["Fare"].sub(dataFrame["Age"]), columns=["Fare Age Diff"])
fare_age_diff

     Fare Age Diff
0         -14.7500
1          33.2833
2         -18.0750
3          18.1000
4         -26.9500
..             ...
886       -14.0000
887        11.0000
888            NaN
889         4.0000
890       -24.2500

[891 rows x 1 columns]

**Rounded Numerical Values to 1 Decimal Place**

In [447]:
num_columns = ["PassengerId", "Survived", "Pclass", "Age", "SibSp", "Parch", "Fare"]
rounded_num_values_df = dataFrame[num_columns]
rounded_num_values_df.apply(lambda i : round(i, 1))

     PassengerId  Survived  Pclass   Age  SibSp  Parch  Fare
0              1         0       3  22.0      1      0   7.2
1              2         1       1  38.0      1      0  71.3
2              3         1       3  26.0      0      0   7.9
3              4         1       1  35.0      1      0  53.1
4              5         0       3  35.0      0      0   8.0
..           ...       ...     ...   ...    ...    ...   ...
886          887         0       2  27.0      0      0  13.0
887          888         1       1  19.0      0      0  30.0
888          889         0       3   NaN      1      2  23.4
889          890         1       1  26.0      0      0  30.0
890          891         0       3  32.0      0      0   7.8

[891 rows x 7 columns]

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

**Convert Genders to Numeric Codes**

In [465]:
num_genders_df = dataFrame["Sex"].map(lambda i: 0 if i == "male" else 1)
num_genders_df

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

**Age Categorizes Column**

In [466]:
def categorize_age(x):
    if x < 18:
        return "child"
    elif x >= 18 and x < 50:
        return "adult"
    else:
        return "senior"

age_categories_df = dataFrame["Age"].map(categorize_age)
age_categories_df

0       adult
1       adult
2       adult
3       adult
4       adult
        ...
886     adult
887     adult
888    senior
889     adult
890     adult
Name: Age, Length: 891, dtype: str

### Part 8 ###
Selected **Part 2.1, Part 3.1, and Part 5.1** to redo in pure Python code

In [476]:
import csv
import urllib.request

url = "https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv"

with urllib.request.urlopen(url) as response:
    lines = [line.decode('utf-8') for line in response]
    dataset_list = list(csv.reader(lines))

**Select Name Column**

In [479]:
name_column = dataFrame["Name"].to_frame()
name_column

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

**Older Than 60**

In [480]:
older_than_60 = dataFrame[dataFrame["Age"] > 60]
older_than_60

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

**New Column of Fares in Euros**

In [481]:
conversion_rate = 0.86
fare_euros_df = dataFrame.copy()
fare_euros_df["Fare Euros"] = fare_euros_df["Fare"] * conversion_rate
fare_euros_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000

**Execution Time Conpared to Pandas Version**

*Pure Python Code:*

*Pandas Code:*